#!/usr/bin/env python3
# Entry point for topology reporting and diffing.
# Usage:
#   python3 ros2_topology_report.py graph.json            # single-snapshot report
#   python3 ros2_topology_report.py old.json new.json     # two-snapshot diff
#
# Pass --out - to write the report to stdout instead of a file.

import argparse
import os
from typing import Set

from lib.common import load_graph
from lib.filters import filter_tool_nodes, filter_transform_listener
from lib.matching import match_nodes
from lib.render import render_diff, render_single, write_report


def _default_out(base_path: str, filename: str) -> str:
    return os.path.join(os.path.dirname(os.path.abspath(base_path)), filename)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=(
            "Generate a topology-oriented report from ros2_graph_snapshot.py output. "
            "Groups nodes by pub/sub signature to compare systems even when node names differ."
        )
    )
    ap.add_argument(
        "graph_json",
        nargs="+",
        help="Path(s) to graph.json generated by ros2_graph_snapshot.py (1=report, 2=diff)",
    )
    ap.add_argument(
        "--out",
        default=None,
        help="Output report path. Default: alongside graph_json as topology.md / topology_diff.md. Use '-' to write to stdout.",
    )
    ap.add_argument("--max-groups", type=int, default=50, help="Max signature groups to print in detail (0=no limit).")
    ap.add_argument(
        "--max-nodes-per-group", type=int, default=10, help="Max node fq_names to show per signature group."
    )
    ap.add_argument("--topic-focus", default=None, help="Regex filter for topics in the topic index section.")
    ap.add_argument(
        "--min-similarity", type=float, default=0.70, help="Min Jaccard similarity for fuzzy node matching (diff mode)."
    )
    ap.add_argument(
        "--min-margin", type=float, default=0.10, help="Min margin vs 2nd-best candidate for uniqueness (diff mode)."
    )
    ap.add_argument(
        "--include-transform-listener",
        action="store_true",
        help="Include transform_listener* nodes (default: ignored).",
    )
    ap.add_argument(
        "--include-parameter-events",
        action="store_true",
        help="Include /parameter_events in matching and diffs (default: ignored).",
    )
    ap.add_argument(
        "--include-tool-nodes",
        action="store_true",
        help="Include /graph_snapshot and /launch_ros_* nodes (default: ignored).",
    )
    ap.add_argument(
        "--include-common-topics",
        action="store_true",
        help="Show /rosout, /clock, /parameter_events in single-report group display (default: hidden).",
    )
    ap.add_argument(
        "--max-match-summary", type=int, default=100, help="Max matched pairs shown in diff summary (0=no limit)."
    )
    ap.add_argument(
        "--max-changed-nodes", type=int, default=200, help="Max changed node entries shown in diff (0=no limit)."
    )

    args = ap.parse_args()

    if len(args.graph_json) not in (1, 2):
        raise SystemExit("Expected 1 (report) or 2 (diff) graph_json paths")

    ignored_topics: Set[str] = set() if args.include_parameter_events else {"/parameter_events"}

    # ── Single-snapshot report ──────────────────────────────────────────────────
    if len(args.graph_json) == 1:
        data, nodes = load_graph(args.graph_json[0])
        nodes = filter_transform_listener(nodes, include=args.include_transform_listener)
        nodes = filter_tool_nodes(nodes, include=args.include_tool_nodes)

        out_path = args.out or _default_out(args.graph_json[0], "topology.md")
        lines = render_single(
            data,
            nodes,
            ignored_topics=ignored_topics,
            src_path=args.graph_json[0],
            include_transform_listener=args.include_transform_listener,
            include_tool_nodes=args.include_tool_nodes,
            include_parameter_events=args.include_parameter_events,
            include_common_topics=args.include_common_topics,
            max_groups=args.max_groups,
            max_nodes_per_group=args.max_nodes_per_group,
            topic_focus=args.topic_focus,
        )
        write_report(lines, out_path)
        if out_path != "-":
            print(out_path)
        return 0

    # ── Two-snapshot diff ───────────────────────────────────────────────────────
    old_path, new_path = args.graph_json[0], args.graph_json[1]
    old_data, old_nodes = load_graph(old_path)
    new_data, new_nodes = load_graph(new_path)
    old_nodes = filter_transform_listener(old_nodes, include=args.include_transform_listener)
    new_nodes = filter_transform_listener(new_nodes, include=args.include_transform_listener)
    old_nodes = filter_tool_nodes(old_nodes, include=args.include_tool_nodes)
    new_nodes = filter_tool_nodes(new_nodes, include=args.include_tool_nodes)

    old_params = old_data.get("param_names", {}) or {}
    new_params = new_data.get("param_names", {}) or {}
    old_param_values = old_data.get("param_values", {}) or {}
    new_param_values = new_data.get("param_values", {}) or {}

    mapping, evidence = match_nodes(
        old_nodes,
        new_nodes,
        min_similarity=args.min_similarity,
        min_margin=args.min_margin,
        old_params=old_params,
        new_params=new_params,
    )

    out_path = args.out or _default_out(new_path, "topology_diff.md")
    lines = render_diff(
        old_path,
        new_path,
        old_data,
        new_data,
        old_nodes,
        new_nodes,
        mapping=mapping,
        evidence=evidence,
        old_params=old_params,
        new_params=new_params,
        old_param_values=old_param_values,
        new_param_values=new_param_values,
        ignored_topics=ignored_topics,
        include_transform_listener=args.include_transform_listener,
        include_tool_nodes=args.include_tool_nodes,
        include_parameter_events=args.include_parameter_events,
        max_match_summary=args.max_match_summary,
        max_changed_nodes=args.max_changed_nodes,
        max_nodes_per_group=args.max_nodes_per_group,
    )
    write_report(lines, out_path)
    if out_path != "-":
        print(out_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
