name: build-and-test

on:
  push:
    branches:
      - main

jobs:
  bnt:
    strategy:
      fail-fast: false
      matrix:
        rosdistro: [humble, jazzy]
        include:
          - rosdistro: humble
            container: ghcr.io/autowarefoundation/autoware:core-devel-humble
          - rosdistro: jazzy
            container: ghcr.io/autowarefoundation/autoware:core-devel-jazzy

    uses: ./.github/workflows/build-and-test-reusable.yaml

    with:
      ros_distro: ${{ matrix.rosdistro }}
      container: ${{ matrix.container }}
      pull-ccache: false
      push-ccache: true
      cache-key-element: build
      codecov-flag: total-${{ matrix.rosdistro }}
      concurrency-group: build-and-test-${{ matrix.rosdistro }}-${{ github.ref }}-${{ github.run_id }}
      runner: "['ubuntu-latest']"

    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
