cmake_minimum_required(VERSION 3.8)
project(husky_sensor_kit_launch)
find_package(ament_cmake REQUIRED)
install(DIRECTORY launch config DESTINATION share/${PROJECT_NAME})
install(PROGRAMS scripts/odom_twist_bridge.py DESTINATION lib/${PROJECT_NAME})
install(PROGRAMS scripts/corrimu_bridge.py DESTINATION lib/${PROJECT_NAME})
install(PROGRAMS scripts/pointcloud_bridge.py DESTINATION lib/${PROJECT_NAME})
install(PROGRAMS scripts/gnss_fix_bridge.py DESTINATION lib/${PROJECT_NAME})
ament_package()
